package org.proyectopokemon.model;

/**
 * ENUMERADO CON LOS ESTADOS QUE PUEDE TENER UN POKEMON
 */
public enum Estado {
    PARALIZADO,QUEMADO,ENVENENADO,GRAVEMENTE_ENVENENADO,DORMIDO,CONGELADO,HELADO,SOMNOLIENTO,POKERUS,DEBILITADO,
    CONFUSO,ENAMORADO,ATRAPADO,MALDITO,DRENADORAS,CANTO_NORMAL,CENTRO_DE_ATENCION,AMEDENTRADO
}